# Generated by Django 5.1.2 on 2024-10-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_category_slug_alter_course_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(to="courses.category"),
        ),
    ]
