# Generated by Django 5.1.2 on 2024-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_course_ishome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
