# Generated by Django 5.1.2 on 2024-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_uploadmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
