# Generated by Django 5.1.2 on 2024-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_slider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
